### ISSUE TITLE
格式化代码的时候遇到单行匿名函数会出现问题

### ISSUE THREAD

**Issue by liyu34** [k0204/LuaIde#100]
下面的代码在进行格式化时，匿名函数后面所有行的代码都会额外缩进一格
```Lua
function test( method )
    return method(1)
end

function main(  )
    local res = test(function(parameter) return parameter+1 end)
end

function VoidFunc(  )
    --Do nothing
end
```
格式化之前：
![image](https://user-images.githubusercontent.com/12342277/33062441-4a92bcf6-ceda-11e7-9cda-6b92be54a469.png)
格式化之后：
![image](https://user-images.githubusercontent.com/12342277/33062491-7087dae0-ceda-11e7-8415-1a3c815a0e61.png)

**Comment by k0204** [comment]
已经修复,0.5.2 版本发布
