### ISSUE TITLE
标签提示时不能正确捕捉类的问题和单引号的问题

### ISSUE THREAD

**Issue by liyu34** [k0204/LuaIde#101]
`BasicClass.lua`文件
```lua
local Status =
{
    on = 1,
    off = 2
}

local This = 
{
}

function This:DoSomething()
{
    --Do something
}

return This
```
如果`BasicCLass`类定义成如上的话，当在其子类中使用@SuperType标签提示时会自动提示为`[BasicClass#Status]`，后面的继承方法提示也会无效，需要手动写为`[BasicClass#This]`。
我想能否确定类名的时候看文件最后返回的是什么来决定这个类在文件里到底叫什么？

---
另外能不能支持require对单引号的支持呢……或者加个设置也好呀，现在`require "BasicClass"`进行跳转的时候可以成功，但是`require 'BasicClass'`进行跳转的时候就会失败。。。
组长写的框架都是用的单引号，没法都改成双引号……代码格式化的时候单双引号能不能也有个设置呢？

**Comment by k0204** [comment]
第一个问题   查看 "luaide.defineModule" 配置

**Comment by k0204** [comment]
第二个问题已经修复  0.5.2 更新

**Comment by liyu34** [comment]
![image](https://user-images.githubusercontent.com/12342277/33247607-4432dc68-d35a-11e7-9dbc-674008264933.png)
现在还是不能通过单引号跳转呀。
