### ISSUE TITLE
启动分析文件导致卡顿

### ISSUE THREAD

**Issue by ilclpj** [k0204/LuaIde#102]
1. 在刚打开lua文件时会对整个workdir进行查找lua文件操作, 如果这时候workdir文件过多会造成查找时间太长, 要是在这过程中启动了调试就会导致整个电脑卡很久. 希望能提供忽略查找某些文件夹的功能或者优化查找, 如果能有缓存就更好了

2. 每次启动调试都会检索文件目录, 如果文件太多会造成启动时间过长, 希望能提供这个检索的忽略文件夹, 如果能缓存, 然后只是检索变动的文件就更好了

**Comment by k0204** [comment]
luaide 的代码提示功能是更加及时分析文件进行的,这一机制开始比较靠谱.对于进行缓存的方案以前考虑过,后期放弃而是直接通过启动程序后及时解析. nodejs 是多进程不会卡主进程影响还是比较小的. 忽略文件夹已经有这个功能了.  
// 忽略的文件夹集合,不会对忽略文件夹中的脚本进行分析
  "luaide.ignoreDir": [], 
查一下这个配置 即可
