### ISSUE TITLE
unity中后缀为.bytes文件的断点会有问题

### ISSUE THREAD

**Issue by yhchen** [k0204/LuaIde#103]
在文件Game.bytes中加断点，会提示Game.b.bytes文件找不到。我的launch.json文件配置如下:
---------------------------------------
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Unity-xlua",
			"type": "lua",
			"request": "attach",
			"runtimeType": "Unity",
			"localRoot": "${workspaceRoot}",
            "fileExtname": ".bytes",
            "port": 7103,
            "checkLuaDebugVersion": true,
			"printType": 1
		}
	]
}
---------------------------------------

目前调试发现是代码原因导致，具体行数是在：
out/src/debugger/LuaDebug.js:472
out/src/debugger/LuaDebug.js:473
-------------------------------
        fileName = fileName.substr(0, fileName.length - 4) + this.fileExtname;
        path = path.substr(0, path.length - 4) + this.fileExtname;
-------------------------------
这两处，注释掉这两行就正常运行

**Comment by k0204** [comment]
已修改
fileName = fileName.substr(0, fileName.length - this.fileExtname.length) + this.fileExtname;
		path = path.substr(0, path.length - this.fileExtname.length) + this.fileExtname;
