### ISSUE TITLE
希望大神紧急修复代码格式化的问题

### ISSUE THREAD

**Issue by hsu2015** [k0204/LuaIde#106]
我们项目比较多，现在格式化问题会导致严重的版本同步问题 @k0204 #104

**Comment by k0204** [comment]
项目进入运营阶段后 开了各种分支 不建议用代码格式化   这样会出现很多冲突   改动可能会很大 , 建议关闭代码自动格式化

**Comment by k0204** [comment]
新版本采用 https://github.com/trixnz/lua-fmt  0.5.6 版本添加
