### ISSUE TITLE
tolua下不能断点了

### ISSUE THREAD

**Issue by lijianghua168** [k0204/LuaIde#112]
更新LuaDebug和LuaDebugjit之前可以断点，更新后就没法断点了。

**Comment by guoweidong1987** [comment]
同样的问题，调试demo已发送至邮箱 3567349380@qq.com

**Comment by guoweidong1987** [comment]
我这ok了，应该是因为刚调完调试代码后面同一调用栈的断点不起作用，之后别的地方断点是OK的
