### ISSUE TITLE
导出api的提示

### ISSUE THREAD

**Issue by ice1989** [k0204/LuaIde#114]
当出现了同名 变量提示的 时候   输入提示可以出来2个 但是选中之后 返回值 依旧只取第一个函数的返回值
--[[
	@type System.Type
	@return [luaIde#UnityEngine.Component]
--]]
function UnityEngine.GameObject:GetComponent(type) end

--[[
	@UILabel UILabel
	@return [luaIde#UILabel]
--]]
function UnityEngine.GameObject:GetComponent(UILabel) end

**Comment by k0204** [comment]
不支持 ,0.5.8 加入新的提示机制  利用命名规则来提示 如果 xxxGo    Go 标示gameobject  那么 xxxGo 拥有gameObject 所以api 提示
