### ISSUE TITLE
打开编辑器时,非.lua结尾的lua脚本不能正常解析

### ISSUE THREAD

**Issue by lovebirdsx** [k0204/LuaIde#12]

**Comment by k0204** [comment]
什么情况下 回以非.lua 后缀 进行编辑能?

**Comment by lovebirdsx** [comment]
所有支持lua的游戏引擎的上层lua脚本文件都得使用.lua为文件扩展名?

**Comment by k0204** [comment]
"files.associations": {
        "*.txt": "lua"
    }
