### ISSUE TITLE
打印的值和断点看到的只不一样

### ISSUE THREAD

**Issue by lijianghua168** [k0204/LuaIde#124]
![qq 20171221181335](https://user-images.githubusercontent.com/34225397/34251355-c83aeafe-e67a-11e7-9bc8-1fe608f58087.png)
断点看到的是nil，但打印出来的是1

**Comment by lijianghua168** [comment]
![qq 20171221181603](https://user-images.githubusercontent.com/34225397/34251435-0aea3530-e67b-11e7-9af1-78a25c5d102b.png)

**Comment by k0204** [comment]
userdata bug 已修复  0.5.8 更新
