### ISSUE TITLE
代码格式化时字符串中有‘\’时仍然会有问题

### ISSUE THREAD

**Issue by guoweidong1987** [k0204/LuaIde#14]
1:采用[[ string  ]]定义字符串时，
2:‘“’。 和”‘“ 会有问题：
3:” \a \x \b“ 之类的一些字符
以上情况格式化时都会出现‘\’数量变化的情况，

在我4月9号提交的pull request中针对解决了上述问题

**Comment by k0204** [comment]
好的晚上回去看看!

**Comment by guoweidong1987** [comment]
我不是去掉了转义符，而是在每个转义符那里又加了一个，这样字符串被js写入文件时正好和从lua中读到的原始字符串完全一致

**Comment by k0204** [comment]
已经用你提供的了下个版本更新上去
