### ISSUE TITLE
监视的问题

### ISSUE THREAD

**Issue by laosigege** [k0204/LuaIde#142]
现在的监视窗口仅仅只能监视变量，也就是说监视应该是从变量窗口里取值的，这样就没有实际的意义了。监视应该是监视表达式，而不是只是变量。可不可以在断点的时候把监视的表达式发送到luadebug.lua，通过计算再发送到监视窗口呢？参考[https://github.com/pkulchenko/MobDebug/tree/master/src](url)    "SETW"

**Comment by k0204** [comment]
程序上能实现,但有个问题 如果执行了某个方法  那么就会改变内存数据!所以综合考虑后没有添加
