### ISSUE TITLE
全局变量颜色设置无效，添加一个控制开关

### ISSUE THREAD

**Issue by JoyHappy** [k0204/LuaIde#148]
// 全局变量颜色
"luaide.golbalFieldColor": "#FF0000",

// 全局方法颜色
"luaide.golbalFunColor": "#FFFF00",

1.全局变量"luaide.golbalFieldColor": "#FF0000"是红色，但实际显示是绿色，而且设置也无效
2.golbal->global
3.建议加上开关，设置这2种颜色替换，节约消耗

**Comment by k0204** [comment]
已修改
