### ISSUE TITLE
现在的todo标签是luaide的功能吗？有点问题

### ISSUE THREAD

**Issue by klkucan** [k0204/LuaIde#151]
使用@符号可以出来很多比如TODO的标签（@TODO 2018-07-03 11:58:27），但是这个代码会提示错误。必须使用【--】注释掉才行。如果是我们的功能，可不可以直接加好 【--】啊

**Comment by k0204** [comment]
--@TODO

**Comment by k0204** [comment]
输入 --@  后会提示 todo
