### ISSUE TITLE
数组内容代码提示支持

### ISSUE THREAD

**Issue by lybugger** [k0204/LuaIde#152]
希望支持如下代码提示：
local A = class(function(self)
 self.m_1 = 1
 self.m_2 = 2
end)
local as = {}
local a = A()
table.insert(a)

希望能提示a[1].m_1

**Comment by k0204** [comment]
这种无法实现  无法知道 你在什么时候 insert  各种情况都会有   没法判断

**Comment by lybugger** [comment]
那希望支持下，标记这个table下所有成员变量为相同类型的标签
比如
--@ SubType[Type]
self.array = {}
这样，我在访问 self.array[1]、self.array["a"]、时可以提示其类型
lua里使用数组还是比较频繁的，标签还没有支持到数组的程度吧

**Comment by k0204** [comment]
--@RefType [ddd#DGS_SummonBossMgr<>]
local data = {}   加入 <> 后代表数组  0.7.3 更新
