### ISSUE TITLE
断点程序运行就卡主

### ISSUE THREAD

**Issue by jj391** [k0204/LuaIde#153]
local breakSocketHandle,debugXpCall = require("Assets/Example/LuaDebug")("localhost",7003)

//这里是加载lua脚本的代码。
//luaScriptName，这个只是lua的文件名，还是lua文件的全路径？两个方法我都试过了。都会卡主。没有报错
        private void loadScript(string script)
        {
            string luaCode = string.Format("require ('{0}');", script);
            //string luaScriptName = m_className + ".lua";
            string luaScriptName = script + ".lua";
            luaEnv.DoString(luaCode, luaScriptName, m_luaView);

        }

**Comment by k0204** [comment]
提供复现案例!

**Comment by jj391** [comment]
决解了。原来是我这里
 "name": "Unity-lua",
            "type": "lua",
            "request": "attach",
            "runtimeType": "Unity",
            "localRoot": "${workspaceRoot}",
            "fileExtname": ".txt",
            "port": 7003,
            "printType": 1

这里的 "fileExtname": ".txt",  没有改成.lua文件后缀

**Comment by k0204** [comment]
好的
