### ISSUE TITLE
希望加个标签能标记一个Table里所有的成员为指定类型

### ISSUE THREAD

**Issue by lybugger** [k0204/LuaIde#155]
local T = class(function(self)
	self.a = 1
	self.b = 2
	self.c = 3
end)

--@RefType [FilePath#T] // 将A的成员全部标记为T类型
local A = {}

A[1] = T()
A[2] = T()
A["a"] = T()

**Comment by k0204** [comment]
local model = {a=1,b=2}
--@RefType [src.game#model<>]
local models = {}
models[1].
当前版本 发现这里数组检查有错误    下个版本将会修复  当前版本 0.7.1
