### ISSUE TITLE
点脚本名字可以跳转，但是点脚本里面的方法就跳转不过去

### ISSUE THREAD

**Issue by ghost** [k0204/LuaIde#157]
A脚本--------------------------------------------------------------
local DGS_HaemalStrandMgr = 
{
	name = 'DGS_HaemalStrandMgr'
}
local instance = nil
function DGS_HaemalStrandMgr.Instance()
	if instance == nil then
	    instance = DGS_HaemalStrandMgr:New()
	end
	return instance
end

function DGS_HaemalStrandMgr:New(o)
	o = o or {}
	setmetatable(o, self)
	self.__index = self
	return o
end

function DGS_HaemalStrandMgr:Start()

end

function DGS_HaemalStrandMgr:CreathaemalStrand()

end
B脚本-------------------------------------------------------------------------------------
local DGS_SummonBossMgr = 
{
	name = 'DGS_SummonBossMgr'
}
local instance = nil
function DGS_SummonBossMgr.Instance()
	if instance == nil then
	    instance = DGS_SummonBossMgr:New()
	end
	return instance
end

function DGS_SummonBossMgr:New(o)
	o = o or {}
	setmetatable(o, self)
	self.__index = self
	return o
end

function DGS_SummonBossMgr:Start()

end

function DGS_SummonBossMgr:OnBossAppearListener()
	DGS_HaemalStrandMgr.Instance():CreathaemalStrand()
end

**Comment by k0204** [comment]
--[[
    @desc: 
    author:k0204
    time:2018-08-03 20:07:37
    --@o: 
    @return [dd#DGS_HaemalStrandMgr]
]]
function DGS_HaemalStrandMgr:New(o)     尝试下 在 New 方法中添加 @return 标签
