### ISSUE TITLE
在table中定义了个key-value，value类型为一个coroutine function，调用时function的断点不会断进去？

### ISSUE THREAD

**Issue by WuAlan** [k0204/LuaIde#159]
类似于这样：
--定义一个从co_func转到coroutine的函数
function A(co_func)
    return function(...)
        local co=coroutine.create(co_func)
        coroutine.resume(co)
    end
end
--实际协程函数
function co_func()
    print "co_func" --断点1在这
    coroutine.yield()
    print "after yield"() --断点2在这
end
--协程函数对应的table
table= {
    action = A(co_func)
}
调用table.action时不会断到断点，但print的内容会输出

**Comment by k0204** [comment]
协程  无法断点 问题已经修复 0.7.3版本 更新!

**Comment by WuAlan** [comment]
感谢大佬~终身会员一发已表支持~
