### ISSUE TITLE
渴望增加自定义api的功能

### ISSUE THREAD

**Issue by ice1989** [k0204/LuaIde#18]
因为不同平台的需求，我们项目是unity的，有一些代码api都是由C# 提供的，原生api是由unity提供的库提供的，还有一些第三方dll库。如果可以自定义api提示，我们就可以直接自己生成这些api出来，在写代码提示的不会那么累 而且还可以做代码检查 是否使用规范 。

**Comment by ice1989** [comment]
之前使用过一个lua IDE 提供的额外api配置如下:
-------------------------------------------------------------------
-- UserDefined: ["YourFunctionName"] = "descryption", 不要忘记最后有个逗号

Lua_UserDefinedFunctions =
{
["LuaSvr"]="类名:LuaSvr",
["LuaSvr.luaState"]= "变量:LuaState  luaState",
["LuaSvr.inited"]= "变量:bool  inited",
["LuaSvr:waitForDebugConnection"]= "方法:waitForDebugConnection(Action complete)",
["LuaSvr:waitForBind"]= "方法:waitForBind(Action<int> tick, Action complete)",
["LuaSvr:init"]= "方法:init(Action<int> tick,Action complete,LuaSvrFlag flag=LuaSvrFlag.LSF_BASIC)",
["LuaSvr:start"]= "方法:start(string main)",["DownQueuest"]="类名:DownQueuest",
["DownQueuest.MAX"]= "变量:int  MAX",
["DownQueuest:OnStartDownAssets"]= "方法:OnStartDownAssets(string ip,Dictionary<string,ResVO> list,DownRequest.DownCompleteDelegate completeFunc, DownRequest.ProcessDelegate processFunc = null,DownRequest.ErrorDelegate errorFunc = null)",
["DownQueuest:Update"]= "方法:Update()",["SceneCommand"]="类名:SceneCommand",
["SceneCommand.SEND"]= "变量:string  SEND",
["SceneCommand.RECEIVE"]= "变量:string  RECEIVE",["UIProgressBar"]="类名:UIProgressBar",
["UIProgressBar.current"]= "变量:UIProgressBar  current",
["UIProgressBar.onDragFinished"]= "变量:OnDragFinished  onDragFinished",
["UIProgressBar.void"]= "变量:delegate  void",
["UIProgressBar.thumb"]= "变量:Transform  thumb",
["UIProgressBar.numberOfSteps"]= "变量:int  numberOfSteps",
["UIProgressBar.onChange"]= "变量:List<EventDelegate>  onChange",
["UIProgressBar.cachedTransform"]= "变量:Transform  cachedTransform",
["UIProgressBar.cachedCamera"]= "变量:Camera  cachedCamera"

---上面的文件结构是用户根据项目的情况 自己生成出来的配置

**Comment by ice1989** [comment]
另外 点击跳转的时候 有一种情况是如下
我有一个lua的文件 叫LuaArray自定义了 Add 这个方法
我在另外一个lua文件里面使用的时候是这样的
local a = LuaArray:new();
a:Add(xxx); 
输入Add的时候 不能自动匹配到LuaArray 这个lua文件里面的Add方法 直接无提示 
建议这里这块需要考虑下 当匹配不到当前文件的方法 可以考虑匹配全局所有的方法 
为什么会基于这个考虑是因为ide无法知道 这个a 是什么东西，只能通过一个较为简单的全部方法查找的方式

**Comment by k0204** [comment]
0.4.5 已经更新
