### ISSUE TITLE
FileUtils::getInstance()->fullPathForFilename() 资源目录不对

### ISSUE THREAD

**Issue by gdbobu** [k0204/LuaIde#19]
提示找不到资源，双击EXE运行是OK的，但是如果用debugLua运行，就报错，找不到资源

**Comment by k0204** [comment]
请查看视频教程 按照教程先做一次

**Comment by gdbobu** [comment]
调试是OK的，就是loadCSB的时候，经过这个函数的运算，然后路径不对了。其他都正常

**Comment by k0204** [comment]
没明白路径不对是什么意思

**Comment by gdbobu** [comment]
路径打印出来是空的，很奇怪，但是直接双击运行可以。用调试运行就是不行

**Comment by gdbobu** [comment]
我已经找出原因了，"localRoot": "${workspaceRoot}\\..\\simulator\\win32", 这个地址必须要设置，否则就会有这个问题
