### ISSUE TITLE
Mac调试时新增断点无法生效，必须重启调试才行

### ISSUE THREAD

**Issue by mini-bix** [k0204/LuaIde#192]
Mac调试时新增断点无法生效，必须重启调试才行

**Comment by k0204** [comment]
是否在定时器中调用了breakSocketHandle




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"server"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月29日(星期五) 上午9:55
收件人:&nbsp;"k0204/LuaIde"<LuaIde@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [k0204/LuaIde] Mac调试时新增断点无法生效，必须重启调试才行 (#192)




Closed #192.
