### ISSUE TITLE
调试时无法正常的进行"单步跳过"操作

### ISSUE THREAD

**Issue by ddpigeon** [k0204/LuaIde#20]
点击单步跳过后, 会直接运行到下个新断点才会停,并不会停在下一行(cocos2dx的lua工程,win系统)

**Comment by k0204** [comment]
请查看视频教程 按照教程先做一次, 确保下载了最新的LuaDebug.lua 并确保 是lua 还是luajit   现在是两个不同的 调试文件

**Comment by ddpigeon** [comment]
嗯 解决了 使用luajit 的调试文件就正常了 谢谢啦~
