### ISSUE TITLE
cocos luajit 在主循环里的代码 动态增删断点 容易出现断不住的情况

### ISSUE THREAD

**Issue by yafacex** [k0204/LuaIde#31]
如题 重现不了可联系我。。qq943100400

**Comment by yafacex** [comment]
![image](https://cloud.githubusercontent.com/assets/7322814/25693614/e1d885d8-30dc-11e7-8353-637c9efe9bad.png)
注释掉图中代码就没事了。
复现方法：先在一个scheduler里下好断点，断住之后删除断点，然后按F5继续程序，然后再在同样的位置下断点，就断不住了。

**Comment by k0204** [comment]
采用luadebugjit 文件即可
