### ISSUE TITLE
很感谢这个插件，一个小建议希望自动对齐的时候缩进tab换为空格(2个或4个可以配置)

### ISSUE THREAD

**Issue by mimicryryu** [k0204/LuaIde#42]
一般我都用两个空格作为缩进对齐，但是一使用插件自动对齐后全部空格都被替换成tab，下次打开自动检测tab size又有可能变成4个空格。希望能增加自动对齐的缩进配置谢谢。

**Comment by k0204** [comment]
收到修改后会在更新列表中说明

**Comment by k0204** [comment]
已添加
