### ISSUE TITLE
调试bug：位于匿名函数中的断点有时无法命中，同时从调用方也StepIn不了

### ISSUE THREAD

**Issue by taigacon** [k0204/LuaIde#46]
非常感谢作者带来这么棒的插件！
然后代码截图如下：
![image](https://user-images.githubusercontent.com/7021624/27079121-0a34d33c-5069-11e7-951c-694993249f4c.png)
![image](https://user-images.githubusercontent.com/7021624/27079039-bd5d4f76-5068-11e7-8fae-b5e6c3f1b6eb.png)
代码在图1中能成功断点，但StepIn无效，类似于StepOver一样自动略过
代码在图2中有一定几率能断点成功（经测试都在grid=nil的时候能断点，不等于nil的时候无法断点）

**Comment by k0204** [comment]
确定用的是lua 还是 luajit   两个调试文件  对应 lua 和 luajit   新版本已经做了判断
