### ISSUE TITLE
错误的 #{...} 提示

### ISSUE THREAD

**Issue by Jayatubi** [k0204/LuaIde#52]
#{...} 是合法语法，表示参数列表中的剩余不定数量参数，{...}表示把这些参数组合成一个数组，#{...}表示获取这个数组的长度，但是插件提示如下错误：
![image](https://user-images.githubusercontent.com/4991045/28158744-538d9d0c-67ed-11e7-9e16-d85eeb25c0e8.png)

**Comment by k0204** [comment]
已经修改
