### ISSUE TITLE
错误的运算符提示

### ISSUE THREAD

**Issue by Jayatubi** [k0204/LuaIde#54]
`//`是5.3里面的`整除`运算符：

````
__idiv - (Lua 5.3) Floor division (division with rounding down to nearest integer). '//' operator.
````
http://lua-users.org/wiki/MetatableEvents

![image](https://user-images.githubusercontent.com/4991045/28296806-009e89d6-6b9d-11e7-8237-6eb2f4c8721d.png)

**Comment by k0204** [comment]
已修改 0.4.4 版本 更新
