### ISSUE TITLE
含有特定内容的代码无法被格式化

### ISSUE THREAD

**Issue by fgc0109** [k0204/LuaIde#55]
类似下面这句含有转义符的字符串

`datainfo = datainfo .. "\n\t\t[\"" .. tostring(key) .. "\"] = \"" .. tostring(userdata) .. "\","`

如果一个文件包含类似的语句，按格式化快捷键不会有任何反应。
没有测试是否还有其他情况不能正确的格式化。

https://github.com/GCCFeli/vscode-lua
这个插件能够正确格式化

但是两个插件不兼容。

**Comment by k0204** [comment]
最近在做各引擎的代码提示库工具 做完后进行修改

**Comment by k0204** [comment]
已经修复,https://github.com/GCCFeli/vscode-lua 这个看了下 是调用的exe 进行格式化的   由于luaide 需要对 多平台进行支持 所以是自己写的 0.5.2 会更新修改内容
