### ISSUE TITLE
Lua某些关键字没有提示

### ISSUE THREAD

**Issue by zhygmsz** [k0204/LuaIde#59]
在设置了"editor.snippetSuggestions": "top"后，写代码的过程中，某些关键字没有提示，经过测试，关键字列表如下and, break, elseif, false, in, nil, not, or, repeat, return, true, until

**Comment by k0204** [comment]
已修改  0.4.4  版本将会发布

**Comment by k0204** [comment]
已修改  0.4.4  版本将会发布
