### ISSUE TITLE
luaIde启动失败,请检查undefined的写入权限

### ISSUE THREAD

**Issue by LaodaLuo** [k0204/LuaIde#67]
win10x64，安装插件后显示这个【luaIde启动失败,请检查undefined的写入权限】，.vscode目录和软件目录的权限检查了没啥问题啊。

**Comment by k0204** [comment]
麻烦给下 调试配置

**Comment by LaodaLuo** [comment]
找到原因：单独打开一个 .lua 文件的时候就会这样。
