### ISSUE TITLE
不同的lua文件中有一样的函数名，跳转会有问题

### ISSUE THREAD

**Issue by JoyHappy** [k0204/LuaIde#73]
比如：
test1.lua
local mgr = {}
function mgr.show()
end

test2.lua
local mgr = {}
function mgr.show()
end
这种跳转会有问题，不知道是不是一定，反正我出现几次了

**Comment by k0204** [comment]
0.4.9 启用第三版跳转 提高了跳转准确率

**Comment by k0204** [comment]
重新修改  设定为  self  或者 self.xxx 会强制检查当前文件 如果当前文件没有再去其他文件中去找 只设定了 两级 原因是为了避免更多情况不能跳转
