### ISSUE TITLE
使用self:funcName()  这样形式调用的函数， 不能跳转到定义

### ISSUE THREAD

**Issue by loutian** [k0204/LuaIde#75]
luaide版本： 收费版0.4.8
lua版本：5.1
代码环境：cocos2dx 3.2
问题描述：
在代码中， 同一个lua文件里， 
self:initDefault()  这样调用， 然后跳转到函数定义， 提示未定义 。   实际上该函数在当前文件已经定义过了。

**Comment by k0204** [comment]
提供 复现的 lua 文件供参考

**Comment by k0204** [comment]
已修改
