### ISSUE TITLE
全局类不能提示里面的函数

### ISSUE THREAD

**Issue by laowai411** [k0204/LuaIde#77]
全局类里面的函数无法提示
![qq 20170914195310](https://user-images.githubusercontent.com/3701745/30428613-d55329cc-9986-11e7-874a-21a911c397ec.jpg)

**Comment by k0204** [comment]
语法错误吧 这里应该直接调用 mainPlayerMoveTo  吧!

**Comment by laowai411** [comment]
不是的，我找到原因了lua源生没有问题，因为我们项目封装了多态类，我们自己项目特性，谢谢你的回答
![111](https://user-images.githubusercontent.com/3701745/30434347-a7c34ef2-9999-11e7-8414-f6394f607aa0.jpg)
