### ISSUE TITLE
Base类里面的函数不能够进行代码提示

### ISSUE THREAD

**Issue by dabaopku** [k0204/LuaIde#84]
local Base = {}

function Base:base()
end

return Base

--[[
    @SuperType [Test.Base#Base]
]]
local Extends = {}

function Extends:extends()
end

return Extends

--[[
    @RefType [Test.Extends#Extends]
]]
local a = {}

在这里, 输入 a:  之后只会提示extends, 不提示base

**Comment by k0204** [comment]
已修改0.4.9 版本更新
