### ISSUE TITLE
使用import做文件依赖的项目无法跳转

### ISSUE THREAD

**Issue by tanzihoho** [k0204/LuaIde#85]
我这边的开发项目  lua文件间的依赖是通过自己封装的一个import函数去实现的
例如
A B 两个文件
---------A------------
function test()
end
---------B------------
a = import("A.lua")
a.test()

这样的话，无法跳转到函数定义，这个有办法支持吗

**Comment by k0204** [comment]
已经加入 import 的支持  import  会先查找传入字符串 的路径是否存在如果不存在将按照当前文件路径进行查找
