### ISSUE TITLE
ulua api 缺少函数标签

### ISSUE THREAD

**Issue by TangQingMing** [k0204/LuaIde#86]
UnityEngine.GameObject.Instantiate

**Comment by k0204** [comment]
看了看 UnityEngine.GameObject.Instantiate c# z中似乎没有导出 麻烦确认下是否有导出   另外的方法
luaide 支持自定义 建立一个文件加入以下代码 即可解决上诉问题
--[[
	@return [luaIde#UnityEngine.GameObject]
]]
function UnityEngine.GameObject:Instantiate() end   这样就能获取到该方法的返回值了
