### ISSUE TITLE
通过http代理上网时，luaide无法启动

### ISSUE THREAD

**Issue by js2854** [k0204/LuaIde#87]
通过http代理上网时，luaide无法启动

![snipaste_20170930_131055](https://user-images.githubusercontent.com/1471787/31042719-d2e0a01e-a5e0-11e7-9d8a-343fc5ac076b.png)

**Comment by k0204** [comment]
服务器腾讯云小水管,如果你是国外的用户 麻烦等等做英文版本的会考虑换服务器!

**Comment by js2854** [comment]
什么意思，我是国内用户，跟服务器没有关系啊，是公司通过http代理上网的情况，装了这个插件，无法联网，用不了
