### ISSUE TITLE
[优化]require提示优化

### ISSUE THREAD

**Issue by maikx2333** [k0204/LuaIde#89]
1。现在按退格键，提示会消失。2.建议恢复旧版，列出完整路径，因为如果有很多相同的名称的文件会一目了然

**Comment by k0204** [comment]
1.这个luaide无法实现,提示信息提交给vscode后进行处理的
2. 0.4.9 添加了 tagIsShowFileName 设置 默认为false 
// 适用于习惯用 M_ 这种方式定义 table 并返回 M_ 时 提示tag标签都显示M_ 设置为true 后显示文件名/M_
  "luaide.tagIsShowFileName": true,
