### ISSUE TITLE
自动补全功能有问题

### ISSUE THREAD

**Issue by Savior666** [k0204/LuaIde#9]
RT
当前自动补全只能提示本文件，而VSCODE自带的自动补全提示是整个项目，期待更新。

**Comment by k0204** [comment]
luaide 是全目录提示的,这里给你解释下吧 vscode 的全目录提示 是将整个项目的代码进行简单的分割 然后将进行提示,而luaide 是根据对应的代码关系进行解析后 进行提示的 而 有些方法是 c++ 或者其他语言中的方法 在lua 中并不存在该方法 所以不会提示. 这也是给你造成的错觉  luaide 只是本文件提示的原因.  后期会加入自定义api 功能 应该能够满足那你的需求
