### ISSUE TITLE
赋值变量不能够推断出类型

### ISSUE THREAD

**Issue by dabaopku** [k0204/LuaIde#91]
[Module.lua.txt](https://github.com/k0204/LuaIde/files/1393309/Module.lua.txt)
[Test.lua.txt](https://github.com/k0204/LuaIde/files/1393310/Test.lua.txt)

输入 **Module.** 后, 可以提示 **test** 这个方法, 但是输入 **Copy.** 之后不能够提示
![2017-10-18 11 18 16](https://user-images.githubusercontent.com/801658/31699545-23534ef6-b389-11e7-8fa1-9fdfa015908b.png)
![2017-10-18 11 18 31](https://user-images.githubusercontent.com/801658/31699546-2392ac04-b389-11e7-91c0-adc709d77a8f.png)

**Comment by k0204** [comment]
已经定位问题并修改 0.5.1 版本发布
