### ISSUE TITLE
代码补全格式问题

### ISSUE THREAD

**Issue by Lony225** [k0204/LuaIde#92]
个人习惯，在函数的参数之间的，后都会加多一个空格
`function test(a, b, c)
end`
一直都保持这个习惯，代码补全出来的直接过滤掉了空格，哪怕我原来的函数定义处用的是我这个格式。
希望能够按照定义处的格式补全就好了。
这个只是我一个强迫症的习惯问题，闲暇有空的时候改一下吧。

谢谢~

**Comment by k0204** [comment]
不好意思每个人都有自己的习惯没法做到大家都合适!改起来不难但是改了大部分人有说他习惯不加空格. 所以暂时不做修改,见谅
