### ISSUE TITLE
使用xlua时，用c#调用lua，调试无法进入断点

### ISSUE THREAD

**Issue by yuechuzhao** [k0204/LuaIde#94]

**Comment by yuechuzhao** [comment]
[xlua_breakdebug.zip](https://github.com/k0204/LuaIde/files/1469532/xlua_breakdebug.zip)
可复现的unitypackage在此。具体内容见邮件

**Comment by k0204** [comment]
关于luaide 调试: c# 通过DoString 进行加载lua脚本无法调试解决方案
LuaBehaviour.cs
将
luaEnv.DoString(luaScript.text, "LuaBehaviour", scriptEnv);
替换为
luaEnv.DoString(luaScript.text, luaScript.name, scriptEnv);

DoString 的第二个参数为chunkName 调试器判断是否断点也是通过这个来确定名字的
上面方案为临时方案(问题在于如果项目中有同名文件调试时会跳转错误,最近会写一个小插件来解决这个问题)
